name: icydesignsllc
favicon: null
layout_spectrum: 0.73172
typography_spectrum: 0.69358
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010000'
    - '#2c2724'
    - '#d4e3e9'
    - '#bea79f'
    - '#9e7d76'
  brandStrength: 0.5
  lightness: 0.3766168754082173
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
